### ISSUE TITLE
Error in rowSums(x)

### ISSUE THREAD

**Issue by bio-lijs** [cresswellkg/SpectralTAD#1]
hi,everyone
there is a problem when using spectralTAD.
![image](https://user-images.githubusercontent.com/52340622/91443839-79914480-e8a6-11ea-97b6-9cca2aaa0148.png)
i used straw or juicertools to extract date from hic format file,bu it always error .

**Comment by mdozmorov** [comment]
Try the following:
- Install `devtools::install_github('dozmorovlab/SpectralTAD')`
- Make sure you have the data formatted as described in the [vignette](https://bioconductor.org/packages/devel/bioc/vignettes/SpectralTAD/inst/doc/SpectralTAD.html). Specifically, you don't have chromosome column, as SpectralTAD works on chromosome-specific sparse matrices.

We will need a minimal reproducible example with data to dig more.

**Comment by bio-lijs** [comment]
thank you~

**Comment by mdozmorov** [comment]
I hope the instructions helped. Please, open another issue if needed
